title: cicconf
author:
  name: Carsten Wulff
  email: carsten@analogicus.com

description: >-
  Simple configuration and revision management for IC projects composed of
  multiple git repositories.
domain: "analogicus.com"
baseurl: "/cicconf"
url: "https://analogicus.com"

show_excerpts: false

minima:
  skin: classic
  social_links:
    - { platform: github, user_url: "https://github.com/wulffern/cicconf" }
    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=uMepikoAAAAJ&hl=en&oi=ao" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/carsten-wulff-1855032/" }
    - { platform: twitter, user_url: "https://twitter.com/cmoswulff" }
    - { platform: youtube, user_url: "https://www.youtube.com/@analogicus" }

markdown: kramdown

kramdown:
  mathjax: true

remote_theme: wulffern/minima
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag
  - jekyll-remote-theme

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
